export const SAVE = 'SAVE';
export const FIND_ALL_WIDGETS = 'FIND_ALL_WIDGETS';
export const FIND_ALL_WIDGETS_BY_TOPIC = 'FIND_ALL_WIDGETS_BY_TOPIC';

export const DELETE_WIDGET = 'DELETE_WIDGET';
export const ADD_WIDGET = 'ADD_WIDGET';
export const HEADING_SIZE_CHANGED = 'HEADING_SIZE_CHANGED';
export const SELECT_WIDGET_TYPE = 'SELECT_WIDGET_TYPE';
export const HEADING_TEXT_CHANGED = 'HEADING_TEXT_CHANGED';
export const HEADING_NAME_CHANGED = 'HEADING_NAME_CHANGED';
export const PREVIEW = 'PREVIEW';
export const MOVE_UP = 'MOVE_UP';
export const MOVE_DOWN = 'MOVE_DOWN';

// export const WIDGET_DRAGGED = 'WIDGET_DRAGGED';
// export const WIDGET_DROPPED = 'WIDGET_DROPPED';



export const PARAGRAPH_TEXT_CHANGED = 'PARAGRAPH_TEXT_CHANGED';
export const PARAGRAPH_NAME_CHANGED = 'PARAGRAPH_NAME_CHANGED';

export const LINK_TEXT_CHANGED = 'LINK_TEXT_CHANGED';
export const LINK_NAME_CHANGED = 'LINK_NAME_CHANGED';
export const LINK_HREF_CHANGED = 'LINK_HREF_CHANGED';

export const IMAGE_TEXT_CHANGED = 'IMAGE_TEXT_CHANGED';
export const IMAGE_NAME_CHANGED = 'IMAGE_NAME_CHANGED';
export const IMAGE_SRC_CHANGED = 'IMAGE_SRC_CHANGED';

export const LIST_ITEMS_CHANGED = 'LIST_ITEMS_CHANGED';
export const LIST_NAME_CHANGED = 'LIST_NAME_CHANGED';
export const LIST_TYPE_CHANGED = 'LIST_TYPE_CHANGED';